### ISSUE TITLE
remove taxon names from branch tips

### ISSUE THREAD

**Issue by andrew-neal** [lczech/gappa#11]
Hi Lucas
I have just switched to gappa after years of using guppy and am enjoying the improvement and additions that you have made.

Is it possible to generate trees without the taxon labels - I notice that you have done this for your publication.  Have I missed a command somewhere?

Many thanks
Andy

**Comment by lczech** [comment]
Hi Andy,

thanks for the positive feedback, glad to hear that gappa is useful!

For my publications, I took the svg trees produced by gappa, and removed the taxon labels manually using [Inkscape](https://inkscape.org/). They are all together in a single svg group, so that is just one click. Generally, I use Inkscape to do a bit of post-processing on the figures to make them look nicer.

I also added your suggestion to my backlog. But it might take a while for me to get to this, as I recently switched positions. So, for the time being, use Inkscape ;-)

Let me know if you have any further suggestions or trouble with gapp!

So long
Lucas

**Comment by andrew-neal** [comment]
Hi Lucas

Thank you for the tip – I’ll give Inkscape a try.

Congratulations on your new position – are you planning on continuing to develop tools associated with phylogenetic placement?  I would be keen to learn more, or try them out for you
Cheers
Andy

**Comment by lczech** [comment]
Hi Andy,

glad that I could help! Will close the issue now, feel free to reopen if you have any more questions.

So, my new position is in a different field, meaning that I probably won't do full-time placement method development any more. But I plan on extending the tools from time to time, and add some quality-of-live things to them. I have a long backlog of ideas that I want to implement, if I have the time. So, stay tuned, but it might take me a while...

Best
Lucas

**Comment by andrew-neal** [comment]
OK – I will keep an eye on your gitgub page to follow up dates.

Also, thanks for the Inkscape tip – it works a treat.

Best wishes
Andy
