### ISSUE TITLE
Query sequences missing in the per_query.tsv file

### ISSUE THREAD

**Issue by miferg** [lczech/gappa#25]
Hi
I used epa-ng to place some read sequences to a referece tree and then used gappa examine assign with the --per-query-results flag to get the per_query.tsv taxonomic classification table.
When checking the results, I found that some sequences are missing from the table but can be found in the jplace file produced by epa-ng. I would like to know if this is expected and/or what could be causing this.
Thanks in advance.
Miguel

**Comment by lczech** [comment]
Hi @miferg,

it could be that those are filtered out for some reason? Unfortunately, I did not write that particular command in gappa - maybe @pierrebarbera is willing to jump in?

Either way, could you please provide the exact command line that causes the issue, and, if possible provide a minimal working example of a jplace file where this error occurs? Otherwise it's hard to track this down.

Thanks and so long
Lucas

**Comment by miferg** [comment]
Hi Lucas,

This is the command line:
```gappa examine assign --jplace-path epang_out/epa_result.jplace --taxon-file deftree.taxstrings.tsv --out-dir tax-classification --per-query-results --allow-file-overwriting```

I'm working on the minimal example.

Thanks
Miguel

**Comment by lczech** [comment]
Hi @miferg, any update on this?

**Comment by lczech** [comment]
Hi @miferg,

I'll close the issue for now, but if you have an update, feel free to re-open or start a new one :-)

Cheers
Lucas
